name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/secure-fullstack-app

jobs:
  # Job 1: CI and Code Security
  ci-security-check:
    runs-on: ubuntu-latest
    # 1. Tell all 'run' commands to execute inside the 'server' folder
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          # REMOVED: cache-dependency-path... (Auto-detection works for root files)

      - name: Install Dependencies
        run: npm ci
        
      # (SAST) - Snyk
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      # Tests (TDD)
      - name: Run Unit & Integration Tests
        run: npm test

      # Secret Scanning
      - name: Secret Scanning with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Job 2: CD and Container Security
  cd-build-push:
    needs: ci-security-check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # Necessário para assinatura (Cosign)

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Lint Dockerfile
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      # Build and Push da Imagem
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}, ${{ env.IMAGE_NAME }}:latest

      # Scan Vulnerability (Container Security)
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
          format: 'table'
          exit-code: '1' # Falha a pipeline se achar erros críticos
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      #  Cosign instalation for image sign (SLSA)
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1

      - name: Sign the published Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        run: |
          echo "$COSIGN_PRIVATE_KEY" > cosign.key
          cosign sign --key cosign.key -y ${{ env.IMAGE_NAME }}:${{ github.sha }}

      # SBOM Generate (SLSA)
      - name: Generate SBOM (Syft)
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          artifact-name: sbom.spdx.json
